services:
  - type: web
    name: eprocurement-scraper
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    healthCheckPath: /
    autoDeploy: true 