services:
  - type: web
    name: eprocurement-scraper
    env: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
      apt-get update -qq
      apt-get install -y -qq wget gnupg ca-certificates
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - > /dev/null 2>&1
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update -qq
      apt-get install -y -qq google-chrome-stable
      google-chrome-stable --version
      ls -l /usr/bin/google-chrome*
      which google-chrome-stable
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
    healthCheckPath: /health
    autoDeploy: true 