services:
  - type: web
    name: eprocurement-scraper
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    healthCheckPath: /health
    autoDeploy: true 